# Generated by Django 5.1.3 on 2024-11-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('Khaki', 'Khaki'), ('Neon', 'Neon'), ('Printed', 'Printed'), ('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Burgundy', 'Burgundy'), ('Green', 'Green'), ('Grey', 'Grey'), ('Navy', 'Navy'), ('Olive', 'Olive'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('White', 'White'), ('Yellow', 'Yellow')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(choices=[('Women', 'Women'), ('Men', 'Men')], max_length=10)),
                ('size', models.CharField(choices=[('0', '0'), ('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18'), ('20', '20'), ('XXXS', 'XXXS'), ('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('1X', '1X')], max_length=5)),
                ('size_type', models.CharField(blank=True, choices=[('Plus Size', 'Plus Size')], max_length=20, null=True)),
                ('category', models.CharField(choices=[('Bodysuits', 'Bodysuits'), ('Long Sleeve Shirts', 'Long Sleeve Shirts'), ('Shirts', 'Shirts'), ('T-Shirts', 'T-Shirts'), ('Tank Tops', 'Tank Tops')], max_length=50)),
                ('collection', models.CharField(blank=True, choices=[('Align', 'Align'), ('All Yours', 'All Yours'), ('Fast & Free', 'Fast & Free'), ('Fundamental', 'Fundamental'), ('Hold Tight', 'Hold Tight'), ('Jersey Training', 'Jersey Training'), ('License To Train', 'License To Train'), ('Love', 'Love'), ('Metal Vent Tech', 'Metal Vent Tech'), ('Sculpt', 'Sculpt'), ('Soft Jersey', 'Soft Jersey'), ('Swiftly', 'Swiftly'), ('Wundermost', 'Wundermost'), ('Zeroed In', 'Zeroed In')], max_length=50, null=True)),
                ('length', models.CharField(blank=True, choices=[('Cropped', 'Cropped'), ('Long', 'Long'), ('Short', 'Short')], max_length=10, null=True)),
                ('fit', models.CharField(blank=True, choices=[('Classic Fit', 'Classic Fit'), ('Relaxed Fit', 'Relaxed Fit'), ('Slim Fit', 'Slim Fit'), ('Tight Fit', 'Tight Fit')], max_length=15, null=True)),
                ('activity', models.CharField(blank=True, choices=[('Casual', 'Casual'), ('Dance', 'Dance'), ('Golf', 'Golf'), ('Hiking', 'Hiking'), ('Running', 'Running'), ('Tennis', 'Tennis'), ('Training', 'Training'), ('Travel', 'Travel'), ('Work', 'Work'), ('Workout', 'Workout'), ('Yoga', 'Yoga')], max_length=20, null=True)),
                ('fabric', models.CharField(blank=True, choices=[('Cotton', 'Cotton'), ('Fleece', 'Fleece'), ('Luon', 'Luon'), ('Mesh', 'Mesh'), ('Nulu', 'Nulu'), ('Pima Cotton', 'Pima Cotton'), ('Ribbed', 'Ribbed'), ('SenseKnit', 'SenseKnit'), ('Softstreme', 'Softstreme'), ('Swift', 'Swift'), ('Wool', 'Wool')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image1_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image2_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image3_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
